server:
  port: 8888
  http2:
    enabled: true
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: config-service
    config:
        import: vault://
    cloud:
        vault:
            token: hvs.zspGxIT1webXqGV9As5B9R9K
            scheme: http
            application-name: config-service
            port: 8200
            host: 127.0.0.1
        config:
            server:
                git:
                    default-label: master
                    clone-on-start: true
                    uri: https://git-lab.ctif.md/mihai.blandu/config-repo.git
                    username: ${gitlabuser}
                    password: ${password}
                    search-paths: '*'




